baseURL = 'https://mubareksd.github.io/'
# website title
title = 'MubarekSD'
# theme
theme = "DoIt"
# [am, ar, en, ti, ...] determines default content language
defaultContentLanguage = "en"
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true