# Menu config

[[main]]
    identifier = "home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    post = ""
    name = "መነሻ"
    url = "/"
    title = ""
    weight = 1

[[main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "ስለ እኔ"
    url = "/about/"
    title = ""
    weight = 2

[[main]]
    identifier = "services"
    pre = ""
    post = ""
    name = "አገልግሎቶች"
    url = "/services/"
    title = ""
    weight = 3

[[main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
    weight = 4
