[home]
    rss = 10
    [home.profile]
        enable = true
        avatarURL = "/images/2-modified.png"
        title = "مبارك سيد جوهر"
        subtitle = "مهندس برمجيات"
        typeit = true
		social = true
    [home.posts]
		enable = true
		paginate = 6

[social]
	Github = "MubarekSD"
	Linkedin = "mubareksd"
	Twitter = "mubareksd"
	Gitlab = "mubareksd"
	phone = "+251951410010"
	Email = "contact@mubareksd.com"
	RSS = true
