description = "Personal blog of Mubarek Seid Juhar"

[app]
	title = "MubarekSD"
	noFavicon = false
	svgFavicon = ""
	themeColor = "#ffffff"
	iconColor = "#5bbad5"
	tileColor = "#da532c"

[search]
	enable = false
	type = "lunr"
	contentLength = 4000
	placeholder = ""
	maxResultLength = 10
	snippetLength = 30
	highlightTag = "em"
	absoluteURL = false

[home]
	rss = 10
	[home.profile]
		enable = true
		gravatarEmail = ""
		avatarURL = "/images/prtotype.png"
		title = "Mubarek Seid Juhar"
		subtitle = "Software Engineer"
		typeit = true
		social = true
		disclaimer = ""
	[home.posts]
		enable = true
		paginate = 6

[social]
	Github = "MubarekSD"
	Linkedin = "mubareksd"
	Twitter = "mubareksd"
	Gitlab = "mubareksd"
	phone = "+251951410010"
	Email = "hello@mubareksd.com"
	RSS = true
