defaultTheme = "auto"
gitRepo = "https://github.com/MubarekSD/mubareksd.github.io"
fingerprint = "sha256"
dateFormat = "2006-01-02"
# website title
title = "MubarekSD"
images = ["/images/2-modified.png"]
# enable PWA
enablePWA = false
license = '<a rel="" href="https://www.gnu.org/licenses/gpl-3.0.en.html" target="_blank">GPL-V3</a>'

[header]
	desktopMode = "fixed"
	mobileMode = "auto"
	[header.title]
		logo = ""
		name = "MubarekSD"
		pre = ""
		post = ""
		typeit = false

[footer]
	enable = true
	custom = ''
	hugo = false
	copyright = true
	author = false
	since = "2017"
	license = '<a rel="" href="https://www.gnu.org/licenses/gpl-3.0.en.html" target="_blank">GPL-V3</a>'

[section]
	paginate = 20
	dateFormat = "01-02"
	rss = 10

[list]
	paginate = 20
	dateFormat = "01-02"
	rss = 10

[page]
	hiddenFromHomePage = false
	hiddenFromSearch = false
	twemoji = false
	lightgallery = false
	ruby = true
	fraction = true
	fontawesome = true
	linkToMarkdown = true
	rssFullText = false
	[page.toc]
		enable = true
		keepStatic = false
		auto = true

	[page.code]
		copy = true
		maxShownLines = 50

	[page.math]
		enable = true
		inlineLeftDelimiter = "$"
		inlineRightDelimiter = "$"
		blockLeftDelimiter = "$$"
		blockRightDelimiter = "$$"
		copyTex = true
		mhchem = true

	[page.share]
		enable = true
		Facebook = true
		Linkedin =true
		Reddit = true
		Telegram = true
		Twitter = true
		Whatsapp = true
	[page.comment]
		enable = true
		[page.comment.disqus]
			enable = true
			shortname = "mubareksd"
	[page.seo]
		image = []
		[page.seo.publisher]
			name = "MubarekSD"
			logoUrl = "/images/prtotype.png"

[typeit]
	speed = 100
	cursorSpeed = 1000
	cursorChar = "|"
	duration = -1

[seo]
	image = "/images/Apple-Devices-Preview.png"
	thumbnailUrl = "/images/screenshot.png"

[analytics]
	enable = true
	[analytics.google]
		id = ""
		anonymizeIP = true

[cookieconsent]
	enable = false
	[cookieconsent.content]
		message = ""
		dismiss = ""
		link = ""

[cdn]
	data = "jsdelivr.yml"

[compatibility]
	polyfill = false
	objectFit = false
