baseURL = 'https://mubareksd.me/'
title = 'MubarekSD'
theme = "loveit"
languageCode = 'en'
disablePathToLower = true
defaultContentLanguage = "en"
languageName = "English"
hasCJKLanguage = false
paginate = 12
googleAnalytics = ""
copyright = "GPL-V3"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
[author]
  name = "Mubarek Seid Juhar"
  email = "mubareksd@gmail.com"
  link = "https://mubareksd.me"

[menu]

[params]
	defaultTheme = "auto"
	gitRepo = "https://github.com/MubarekSD/mubareksd.github.io"
	fingerprint = "sha256"
	dateFormat = "2006-01-02"
	title = "MubarekSD"
	description = "my portfolio"
	images = ["/images/prototype.png"]

	[params.header]
		desktopMode = "fixed"
		mobileMode = "auto"
		[params.header.title]
			logo = ""
			name = "MubarekSD"
			pre = ""
			post = ""
			typeit = false

	[params.footer]
		enable = true
		custom = ''
		hugo = false
		copyright = true
		author = true
		since = "2017"
		license = '<a rel="license external nofollow noopener noreffer" href="https://www.gnu.org/licenses/gpl-3.0.en.html" target="_blank">GPL-V3</a>'

	[params.section]
		paginate = 20
		dateFormat = "01-02"
		rss = 10

	[params.list]
		paginate = 20
		dateFormat = "01-02"
		rss = 10

	[params.app]
		title = "MubarekSD"
		noFavicon = false
		svgFavicon = ""
		themeColor = "#ffffff"
		iconColor = "#5bbad5"
		tileColor = "#da532c"

	[params.search]
		enable = false
		type = "lunr"
		contentLength = 4000
		placeholder = ""
		maxResultLength = 10
		snippetLength = 30
		highlightTag = "em"
		absoluteURL = false

	[params.home]
		rss = 10
		[params.home.profile]
			enable = true
			gravatarEmail = ""
			avatarURL = "/images/profile.jpg"
			title = "Software Engineer"
			subtitle = ""
			typeit = true
			social = true
			disclaimer = ""
		[params.home.posts]
			enable = false
			paginate = 6

	[params.social]
		Github = "MubarekSD"
		Linkedin = "mubareksd"
		Twitter = "mubareksd"
		Facebook = "mubareksd"
		Gitlab = "mubareksd"
		Whatsapp = "+251975273470"
		discord = "1011661556569866250"
		matrix = "@mubareksdd:matrix.org"
		Telegram = "mubareksd"
		phone = "+251975273470"
		Email = "mubareksd@gmail.com"
		RSS = true

	[params.page]
		hiddenFromHomePage = false
		hiddenFromSearch = false
		twemoji = false
		lightgallery = false
		ruby = true
		fraction = true
		fontawesome = true
		linkToMarkdown = true
		rssFullText = false
		[params.page.toc]
			enable = true
			keepStatic = false
			auto = true

		[params.page.code]
			copy = true
			maxShownLines = 50

		[params.page.math]
			enable = true
			inlineLeftDelimiter = "$"
			inlineRightDelimiter = "$"
			blockLeftDelimiter = "$$"
			blockRightDelimiter = "$$"
			copyTex = true
			mhchem = true

		[params.page.share]
			enable = true
			Twitter = true
			Facebook = true
			Linkedin =true
			Reddit = true
			Line = false
			weibo = false
			HackerNews = false
		[params.page.comment]
			enable = true
			[params.page.comment.disqus]
				enable = true
				shortname = "mubareksd"
		[params.page.seo]
			image = []
			[params.page.seo.publisher]
				name = "MubarekSD"
				logoUrl = "/images/prtotype.png"

	[params.typeit]
		speed = 100
		cursorSpeed = 1000
		cursorChar = "|"
		duration = -1
	
	[params.seo]
		image = "/images/Apple-Devices-Preview.png"
		thumbnailUrl = "/images/screenshot.png"

	[params.analytics]
		enable = true
		[params.analytics.google]
			id = ""
			anonymizeIP = true

	[params.cookieconsent]
		enable = false
		[params.cookieconsent.content]
			message = ""
			dismiss = ""
			link = ""

	[params.cdn]
		data = "jsdelivr.yml"

	[params.compatibility]
		polyfill = false
		objectFit = false

[markup]
	[markup.highlight]
		codeFences = true
		guessSyntax = true
		lineNos = true
		lineNumbersInTable = true
		noClasses = false
		[markup.goldmark]
			[markup.goldmark.extensions]
				definitionList = true
				footnote = true
				linkify = true
				strikethrough = true
				table = true
				taskList = true
				typographer = true
			[markup.goldmark.renderer]
				unsafe = true
		[markup.tableOfContents]
			startLevel = 2
			endLevel = 6

[sitemap]
	changefreq = "daily"
	filename = "sitemap.xml"
	priority = 0.5

[Permalinks]
  posts = ":filename"

[privacy]
  [privacy.googleAnalytics]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
	home = ["HTML", "RSS", "JSON"]
	page = ["HTML", "MarkDown"]
	section = ["HTML", "RSS"]
	taxonomy = ["HTML", "RSS"]
	taxonomyTerm = ["HTML"]
